
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("C:/Users/T NAMRATHA PADIYAR/cs/delivery_analytics_project/data/delivery_dataset.csv")   # <-- Change file name if need
print("\n=== SAMPLE DATA ===")
print(df.head())
courier_delay = df.groupby("courier")["delay_days"].mean().sort_values(ascending=False)

print("\n=== COURIER AVERAGE DELAY ===")
print(courier_delay)
courier_delay.plot(kind='bar')
plt.title("Average Delivery Delay by Courier")
plt.ylabel("Average Delay (Days)")
plt.xlabel("Courier")
plt.xticks(rotation=45)
plt.show()

city_delay = df.groupby("city")["delay_days"].mean().sort_values(ascending=False)
print("\n=== CITY AVERAGE DELAY ===")
print(city_delay)
city_delay.plot(kind='bar')
plt.title("Average Delivery Delay by City")
plt.ylabel("Average Delay (Days)")
plt.xlabel("City")
plt.xticks(rotation=45)
plt.show()

category_delay = df.groupby("category")["delay_days"].mean().sort_values(ascending=False)
print("\n=== CATEGORY AVERAGE DELAY ===")
print(category_delay)
category_delay.plot(kind='bar', color='green')
plt.title("Average Delivery Delay by Category")
plt.ylabel("Average Delay (Days)")
plt.xlabel("Category")
plt.xticks(rotation=45)
plt.show()

df["order_date"] = pd.to_datetime(df["order_date"], errors="coerce")
df["month"] = df["order_date"].dt.to_period("M")
month_delay = df.groupby("month")["delay_days"].mean()
print("\n=== MONTHLY DELAY TREND ===")
print(month_delay)
month_delay.plot(kind='line', marker='o')
plt.title("Monthly Delivery Delay Trend")
plt.ylabel("Average Delay (Days)")
plt.xlabel("Month")
plt.grid(True)
plt.show()

zone_delay = df.groupby("zone")["delay_days"].mean().sort_values(ascending=False)
print("\n=== ZONE AVERAGE DELAY ===")
print(zone_delay)
zone_delay.plot(kind="barh", color='orange')
plt.title("Zone-wise Delivery Delay")
plt.xlabel("Average Delay (Days)")
plt.ylabel("Zone")
plt.show()
